project_name: armada
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    main: cmd/armada/main.go
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
    - go mod tidy
dockers:
- image_templates: 
  - "ljubon/armada:{{ .Version }}"
  - "ljubon/armada:latest"
  dockerfile: ./build/armada/Dockerfile
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.description={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/ljubon/armada
  - --label=org.opencontainers.image.source=https://github.com/ljubon/armada
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  use_buildx: true
  extra_files:
    - glob: ./config/armada/config.yaml
    - glob: ./bin/linux/*
